
export const svgConfig =
{
  error404: 'images/404.svg',
  accountCircleIcon: 'images/account-circle-icon.svg',
  addJobApplicationIcon: 'images/add-job-application-icon.svg',
  appliedJobsIcon: 'images/applied-jobs-icon.svg',
  arrowDropDownIcon: 'images/arrow-drop-down-icon.svg',
  cancelIcon: 'images/cancel-icon.svg',
  checkCircleIcon: 'images/check-circle-icon.svg',
  closeIcon: 'images/close-icon.svg',
  darkModeIcon: 'images/dark-mode-icon.svg',
  dashboardIcon: 'images/dashboard-icon.svg',
  errorIcon: 'images/error-icon.svg',
  landingPageLogo: 'images/landing-page-logo.svg',
  leftPanelCloseIcon: 'images/left-panel-close-icon.svg',
  leftPanelOpenIcon: 'images/left-panel-open-icon.svg',
  lightModeIcon: 'images/light-mode-icon.svg',
  logo: 'images/logo.svg',
  logoutIcon: 'images/logout-icon.svg',
  monitoringIcon: 'images/monitoring-icon.svg',
  mobileMenuIcon: 'images/segment-icon.svg',
  editIcon: 'images/edit-icon.svg',
  sendIcon: 'images/send-icon.svg',
  loginIcon: 'images/send-icon.svg',
  demoIcon: 'images/hands-free-icon.svg',
  registerIcon: 'images/app-registration-icon.svg',
  paginationFirstPageIcon: 'images/first-page-icon.svg',
  paginationLastPageIcon: 'images/last-page-icon.svg',
  paginationNextPageIcon: 'images/chevron-forward-icon.svg',
  paginationPrevPageIcon: 'images/chevron-backward-icon.svg',
  clearIcon: 'images/clear-all-icon.svg',
  deleteIcon: 'images/delete-icon.svg',
  visibilityIcon: 'images/visibility-icon.svg',
};

export type SvgNameType = keyof typeof svgConfig;