name: 'Setup Node.js Environment'
description: 'Checkout code, setup Node.js with caching, and install dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '22'
  working-directory:
    description: 'Working directory for npm operations'
    required: true
  cache-dependency-path:
    description: 'Path to package-lock.json for caching'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci --prefer-offline --no-audit
