FROM node:22-alpine

RUN apk --no-cache update

WORKDIR /usr/src/app

# Copy root files and install dependencies for all workspaces
COPY backend/package*.json .
RUN npm ci

# Copy source code
COPY backend .

# Set environment variables for development
ENV NODE_ENV=development

EXPOSE 3001

CMD ["npm", "run", "dev"]