name: Build and Publish Docker Image
description: 'Builds and publishes a Docker image to a specified container registry.'

inputs:
  registry:
    description: 'Container registry to push the image to'
    required: true
  username:
    description: 'Username for the container registry'
    required: true
  password: 
    description: 'Password or token for the container registry'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true
  image_version:
    description: 'Version tag for the Docker image'
    required: true
  image_title:
    description: 'Title label for the Docker image'
    required: false
    default: 'Custom Docker Image'
  context:
    description: 'Build context for the Docker image'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  target:
    description: 'Build target stage in the Dockerfile'
    required: false
  platforms:
    description: 'Target platforms for the Docker image'
    required: false
    default: 'linux/amd64'
  push:
    description: 'Whether to push the image to the registry'
    required: false
    default: 'false'
  publish_latest:
    description: 'Whether to also tag the image as latest'
    required: false
    default: 'false'

outputs:
  image_tags:
    description: 'Tags of the published Docker image'
    value: ${{ steps.build_and_push.outputs.tags }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=latest,enable=${{ inputs.publish_latest == 'true' }}
          type=raw,value=${{ inputs.image_version }}
          type=semver,pattern={{version}},value=${{ inputs.image_version }}
          type=sha,prefix=sha-
        labels: |
          org.opencontainers.image.title=${{ inputs.image_title }}
          org.opencontainers.image.description=Docker image built via GitHub Actions
    - name: Build and push Docker image
      id: build_and_push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: ${{ inputs.push == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: ${{ inputs.platforms }}